metrics:
  serviceMonitor:
    enabled: true
    interval: 30s

defaultSettings:
  defaultReplicaCount: 1
  storageReservedPercentageForDefaultDisk: 30

persistence:
  defaultClassReplicaCount: 1

longhornUI:
  replicas: 1

ingress:
  enabled: true
  ingressClassName: nginx-internal
  host: longhorn.home
  path: /
  pathType: Prefix

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi