repositories:
  - name: longhorn
    url: https://charts.longhorn.io
  - name: metallb
    url: https://metallb.github.io/metallb

environments:
  default:
    values:
      - environments/production/values.yaml

helmDefaults:
  # when using helm 3.2+, automatically create release namespaces if they do not exist (default true)
  createNamespace: true
  # performs pods restart for the resource if applicable (default false)
  recreatePods: true
  # wait for k8s resources via --wait. (default false)
  wait: true
  timeout: 600

helmfiles:
  - path: releases/metallb/helmfile.yaml # metallb
  - path: releases/ingress-nginx/helmfile.yaml # ingress-nginx
  - path: releases/pihole/helmfile.yaml # pihole
  - path: releases/external-dns/helmfile.yaml # external-dns
  # - path: releases/longhorn/helmfile.yaml # longhorn distribute storage
