---
repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: lgtm
    namespace: monitoring
    createNamespace: true
    chart: grafana/lgtm-distributed
    version: 2.1.0
    values:
      - values.yaml