persistentVolumeClaim:
  enabled: false

# -- default upstream DNS 1 server to use
DNS1: "1.1.1.1"
# -- default upstream DNS 2 server to use
DNS2: "192.168.1.1"

ingress:
  enabled: true
  hosts:
    - "pihole.home"
serviceWeb:
  loadBalancerIP: 192.168.1.250
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
serviceDns:
  loadBalancerIP: 192.168.1.250
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
replicaCount: 1

extraVolumes:
  pihole-custom-list:
    configMap:
      name: pihole-custom-list

extraVolumeMounts:
  pihole-custom-list:
    mountPath: /etc/pihole/custom.list
    subPath: custom.list
    readOnly: false

extraObjects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: pihole-custom-list
      namespace: infra
    data:
      custom.list: |
        192.168.1.2 nas.home
        192.168.1.200 litellm.home

resources:
  requests:
    cpu: 150m
    memory: 256Mi
  limits:
    cpu: 300m
    memory: 512Mi