provider: pihole
policy: upsert-only
txtOwnerId: "homelab"
pihole:
  server: http://pihole-web.infra.svc.cluster.local
extraEnvVars:
  - name: EXTERNAL_DNS_PIHOLE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: pihole-password
        key: password
serviceAccount:
  create: true
  name: "external-dns"
ingressClassFilters:
  - nginx-internal
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi