repositories:
  - name: metallb
    url: https://metallb.github.io/metallb

releases:
  - name: metallb
    namespace: metallb-system
    chart: metallb/metallb
    version: 0.14.9
    values:
      - values.yaml
    hooks:
      - events: ["postsync"]
        command: 'bash'
        args:
          - '{{ requiredEnv "PWD" }}/releases/metallb/config.sh'
        showlogs: true