repositories:
  - name: kubernetes-sigs
    url: https://kubernetes-sigs.github.io/external-dns/

releases:
  - name: externaldns
    namespace: infra
    chart: kubernetes-sigs/external-dns
    version: 1.20.0
    values:
      - values.yaml
