provider:
  name: pihole

registry: noop
policy: upsert-only

sources:
  - service
  - gateway-httproute

extraArgs:
  pihole-server: http://pihole-web.infra.svc.cluster.local
  pihole-api-version: "6"

env:
  - name: EXTERNAL_DNS_PIHOLE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: pihole-password
        key: password

serviceAccount:
  create: true
  name: external-dns

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
