releases:
  - name: metallb
    namespace: infra
    chart: metallb/metallb
    version: 0.14.9
    values:
      - values.yaml
    hooks:
      - events: ["postsync","post-apply"]
        command: '{{ env "HELMFILE_ROOT" }}/releases/metallb/config.sh'
        showlogs: true