releases:
  - name: metallb
    namespace: metallb-system
    chart: metallb/metallb
    version: 0.14.9
    values:
      - values.yaml
    hooks:
      - events: ["postsync"]
        command: '{{ env "HELMFILE_ROOT" }}/releases/metallb/config.sh'
        showlogs: true