prometheusRule:
  enabled: true

crds:
  enabled: true

speaker:
  # ignore the exclude-from-external-loadbalancer label
  ignoreExcludeLB: true
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

controller:
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi